### ISSUE TITLE
Steps to execute your makefile

### ISSUE THREAD

**Issue by srivav19** [Securezapp/p7zip-aws-lambda-layer#1]
Relatively new to this.
Can you please provide the steps and where to execute the MakeFile

**Comment by jhecking** [comment]
You can run `make build` to build the package for the Lambda layer in `build/layer.zip` or you can run `make publish` to build the package, and then publish it to your own AWS account.

Note: We are no longer using this Lambda layer in our own projects. We are now using the [archiver package](https://www.npmjs.com/package/archiver) with the [archiver-zip-encrypted plugin](https://www.npmjs.com/package/archiver-zip-encrypted) instead. Therefore, I am going to archive this repo. (No pun intended.)
